name: Post welcome comment
on: 
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  welcome:
    name: Post welcome comment
    runs-on: ununtu-latest
    steps:
      - run: gh pr comment "PR_URL" --body "welcome to the repository"
        env: 
          GITHUB_TOKEN: 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
          PR_URL: https://github.com/shivakumar-186/CodingAssignments/pulls

